### ISSUE TITLE
Suggestion for improving the quick start samples docs

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-aspnetcore-sample#18]
___I will limit this to the scope of the **[01-Login](https://github.com/auth0-samples/auth0-aspnetcore-sample/tree/vs2017/01-Login)** sample, although my suggestion should affect all samples.___
***

The section describing how to **[Add Login and Logout Links](https://auth0.com/docs/quickstart/webapp/aspnet-core/01-login#add-login-and-logout-methods)** describes the code for the **[AccountController](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Controllers/AccountController.cs)**.

In particular it defines the **`Login()`** and **`Logout()`** methods:

```
        public IActionResult Login(string returnUrl = "/")
        {
             ...
        }

        [Authorize]
        public async Task Logout()
        {
            ***
        }
```

This information is tightly related to the section **Configure Callback URLs** in the **[ASP.NET Core Introduction](https://auth0.com/docs/quickstart/webapp/aspnet-core)** article in the sense that the strings:

1. Allowed Callback URL:  **`http://localhost:60856/signin-auth0`**
2.  Allowed Logout URLs: **`http://localhost:8000/signout-auth0`**

look like "routes" to the **`Login()`** and **`Logout()`** methods, defined above. 

My point is this: it is not obvious what is the "mapping" that results that click on the **[Login link](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Views/Shared/_Layout.cshtml#L42)** requires the presence of  configuration setting **`http://localhost:60856/signin-auth0`** in my **[client settings](https://manage.auth0.com/#/clients)**. 

**In the case this is insufficiently clear, let me be more precise:**

Click on the  **[Login link](https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/vs2017/01-Login/SampleMvcApp/Views/Shared/_Layout.cshtml#L42)**, results with the execution of this line

```
return new ChallengeResult("Auth0", new AuthenticationProperties() { RedirectUri = returnUrl });
```

The next action is the execution of the Auth0 Lock widget - and I would like to know more what happens upon successful authentication and how is the callback URL:  **`http://localhost:60856/signin-auth0`** involved in this story.

**Most direct question:**
The strings **`signin-auth0`** and **`signout-auth0`** are seemingly "fixed words". If so, what is the "background story" on them.

**Comment by adriatic** [comment]
The information in http://benfoster.io/blog/aspnet-core-multi-tenant-middleware-pipelines might be used as the inspiration for the additional explanations I am hoping for. 

I am not being lazy to create a PR as Nico suggested; instead, there ought to be more experienced Auth0 folks that are also talented writers to describe what is happening here.

**Comment by jerriep** [comment]
@adriatic 

**http://localhost:60856** or **http://localhost:8000** would be the URL for your application. The path **signin-auth0** is the path on which the OIDC middleware listens for the callback from Auth0. This is specified when you register the OIDC middleware:
https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/master/01-Login/SampleMvcApp/Startup.cs#L91

The flow is as follows:
1. The user clicks on the Login link and is directed to the **Login()** route 
2. This returns a `ChallengeResult` which instructs the ASP.NET Authentication middleware to issue a challenge to the Authentication middleware which is registered with the `authenticationScheme` of **Auth0**. When we created the instance of `OpenIdConnectOptions` on Line 73 (https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/master/01-Login/SampleMvcApp/Startup.cs#L73) we passed a value of **Auth0** to the constructor. This is the **authentication scheme**, so that is why the authentication middleware knows to challege this OIDC middleware to authenticate the user
3. At this point the OIDC middleware is challenged, and it will redirect the user to the Auth0 `/authorize` endpoint, which will display Lock and require the user to sign in - whether it be with username/password, social provider or any other Identity Provider.
4. Once the user has signed in, Auth0 will call back to the `/signin-auth0` endpoint in your application and pass along an authorization code.
5. The OIDC middleware will "listen" for any request made to the `/signin-auth0` path and intercept it. It will look for the authorization code which Auth0 sent in the query string and then call the `/oauth/token` endpoint to exchange the authorization code for an `id_token` and `access_token`.
6. The OIDC middleware will look at the `id_token` and extract the user information from the claims on the token. (However, depending on how your OIDC middleware is configure it may actually get the user information by making a call to the Auth0 `/userinfo` endpoint to get the user claims - https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs#L117)

I will see about adding a little diagram explaining this in our quickstart. Thank you for pointing out that this is not clear.

**Comment by adriatic** [comment]
Thanks, @jerriep 😄 

Your statement

> The path signin-auth0 is the path on which the OIDC middleware listens for the callback from Auth0. This is specified when you register the OIDC middleware:
https://github.com/auth0-samples/auth0-aspnetcore-sample/blob/master/01-Login/SampleMvcApp/Startup.cs#L91

is really the explanation that I was looking for. In all seriousness, I could have realized this without asking, as I looked at the code for setting OIDC middleware **many times more than once**, so it seems that I did not trigger on  

```
               ...
               // Set the callback path, so Auth0 will call back to http://localhost:8000/signin-auth0 
                // Also ensure that you have added the URL as an Allowed Callback URL in your Auth0 dashboard 
                CallbackPath = new PathString("/signin-auth0")
                ...
```

In other words, I did not like the "God given"  (hard-coded) string **`signin-auth0`** until now. 

Naturally, your description of the flow in this situation is terrific and makes me very happu 😏
